### ISSUE TITLE
issues on kde plasma manjaro/arch

### ISSUE THREAD

**Issue by legendofmiracles** [trigg/DiscordOverlayLinux#39]
So i wanted to test this out, but always when i try to execute the binary, it returns this error:
```
❯ python ~/.local/bin/discord-overlay
Traceback (most recent call last):
  File "/home/legendofmiracles/.local/bin/discord-overlay", line 5, in <module>
    from discord_overlay.discord_overlay import *
  File "/home/legendofmiracles/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/legendofmiracles/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /home/legendofmiracles/.local/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5
```
i have found a similar error on the arch forums: https://bbs.archlinux.org/viewtopic.php?id=198691
and also a very similar on on this github issue: https://github.com/mu-editor/mu/issues/575

my python version:
```
❯ python --version
Python 3.8.3
```
```
❯ pip --version
pip 20.0.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

and my installed packages in pip:

```
❯ pip list
Package                Version     Location                        
---------------------- ----------- --------------------------------
absl-py                0.9.0       
aiohttp                3.6.2       
Airshare               0.1.2       
altgraph               0.17        
apparmor               2.13.4      
appdirs                1.4.4       
application-utility    1.3.2       
asn1crypto             1.3.0       
astroid                2.3.3       
astunparse             1.6.3       
async-timeout          3.0.1       
asyncio                3.4.3       
attrs                  19.3.0      
autopep8               1.5.1       
awscli                 1.18.67     
bauh                   0.9.4       
bcrypt                 3.1.7       
beautifulsoup4         4.8.2       
boto                   2.49.0      
boto3                  1.13.16     
botocore               1.16.16     
Brlapi                 0.7.0       
bs4                    0.0.1       
btrfsutil              1.2.0       
CacheControl           0.12.6      
cached-property        1.5.1       
cachetools             4.1.0       
ceph-volume            1.0.0       
cephfs                 2.0.0       
cephfs-shell           0.0.1       
certifi                2020.4.5.1  
cffi                   1.13.2      
chardet                3.0.4       
cheat                  2.5.1       
Click                  7.0         
colorama               0.4.3       
contextlib2            0.6.0.post1 
cryptography           2.8         
cupshelpers            1.0         
cycler                 0.10.0      
decorator              4.4.2       
discordoverlaylinux    0.0.1       
distlib                0.3.0       
distro                 1.5.0       
dnd-tools              0.1.5       
docker                 4.2.1       
docker-compose         1.25.5      
docker-pycreds         0.4.0       
dockerpty              0.4.1       
docopt                 0.6.2       
docutils               0.15.2      
evdev                  1.3.0       
Flask                  1.1.1       
future                 0.18.2      
gast                   0.3.3       
gitdb                  4.0.5       
GitPython              3.1.2       
glitch-this            0.1.5       
google-auth            1.14.0      
google-auth-oauthlib   0.4.1       
google-pasta           0.2.0       
gpg                    1.13.1      
greenlet               0.4.15      
grpcio                 1.28.1      
h5py                   2.10.0      
html5lib               1.0.1       
humanize               2.4.0       
idna                   2.9         
ifaddr                 0.1.6       
imageio                2.8.0       
importlib-metadata     1.6.0       
iotop                  0.6         
iso8601                0.1.12      
isort                  4.3.21      
itsdangerous           1.1.0       
Jinja2                 2.10.3      
jmespath               0.10.0      
joblib                 0.14.1      
jsonschema             3.2.0       
Keras                  2.3.1       
Keras-Applications     1.0.8       
Keras-Preprocessing    1.1.0       
keylogger              2.7.3       
keyutils               0.6         
kiwisolver             1.1.0       
lazy-object-proxy      1.4.3       
lensfun                0.3.95      
LibAppArmor            2.13.4      
libvirt-python         6.4.0       
louis                  3.14.0      
lutris                 0.5.6       
lxml                   4.5.1       
Markdown               3.2.1       
MarkupSafe             1.1.1       
matplotlib             3.2.0       
mccabe                 0.6.1       
minigalaxy             0.9.4       
more-itertools         8.2.0       
msgpack                1.0.0       
multidict              4.7.5       
mwparserfromhell       0.5.4       
neovim                 0.3.1       
networkx               2.4         
npyscreen              4.10.5      
numpy                  1.18.1      
oauthlib               3.1.0       
opt-einsum             3.2.1       
ordered-set            3.1.1       
packaging              20.4        
pacman-mirrors         4.16.4      
paramiko               2.7.1       
path-and-address       2.0.1       
pep517                 0.8.2       
Phyme                  0.0.9       
Pillow                 6.2.1       
pip                    20.0.2      
playx                  1.5.2       /usr/lib/python3.8/site-packages
pluggy                 0.13.1      
ply                    3.11        
pngminifier            1.0.4       
powerline-status       2.8.dev9999 
progress               1.5         
protobuf               3.11.3      
psutil                 5.7.0       
pwquality              1.4.2       
py                     1.8.1       
pyaml                  20.4.0      
pyasn1                 0.4.8       
pyasn1-modules         0.2.8       
pycairo                1.19.1      
pycodestyle            2.5.0       
pycparser              2.19        
pycryptodome           3.9.7       
pycups                 2.0.1       
pycurl                 7.43.0.4    
Pygments               2.6.1       
PyGObject              3.36.1      
pyinstall              0.1.4       
PyInstaller            3.6         
pylint                 2.4.4       
PyNaCl                 1.3.0       
pynvim                 0.4.1       
pyOpenSSL              19.1.0      
pyparsing              2.4.7       
pyperclip              1.8.0       
PyQt-builder           1.4.0       
PyQt5                  5.15.0      
PyQt5-sip              12.8.0      
PyQtWebEngine          5.15.0      
pyrsistent             0.16.0      
pyserial               3.4         
PySide2                5.15.0      
pysmbc                 1.0.20      
PySocks                1.7.1       
pyte                   0.8.0       
pytest                 5.4.1       
python-dateutil        2.8.1       
pytoml                 0.1.21      
pytransloadit          0.1.10      
pyusb                  1.0.2       
PyWavelets             1.1.1       
pyxdg                  0.26        
pyxelate               1.1.2       
PyYAML                 5.3.1       
rados                  2.0.0       
rbd                    2.0.0       
reportlab              3.5.42      
requests               2.23.0      
requests-oauthlib      1.3.0       
requests-toolbelt      0.9.1       
retrying               1.3.3       
rgw                    2.0.0       
rpm                    4.15.1      
rsa                    4.0         
s3transfer             0.3.3       
scikit-image           0.16.2      
scikit-learn           0.22.1      
scipy                  1.4.1       
selenium               3.141.0     
serial                 0.0.97      
setuptools             47.1.1      
shiboken2              5.15.0      
sip                    4.19.22     
six                    1.15.0      
smmap                  3.0.4       
soupsieve              1.9.5       
systemd-python         234         
team                   1.0         
tensorboard            2.2.1       
tensorboard-plugin-wit 1.6.0.post3 
tensorflow             2.2.0rc4    
tensorflow-estimator   2.2.0       
termcolor              1.1.0       
texttable              1.6.2       
thefuck                3.30        
tinydb                 4.1.1       
toml                   0.10.1      
torbrowser-launcher    0.3.2       
tqdm                   4.46.0      
tuspy                  0.2.4       
udiskie                2.2.0       
ufw                    0.36        
urllib3                1.25.9      
wcwidth                0.1.9       
webencodings           0.5.1       
websocket-client       0.57.0      
Werkzeug               0.16.0      
wheel                  0.34.2      
wordcloud              1.7.0       
wrapt                  1.11.2      
xlib                   0.21        
yarl                   1.4.2       
youtube-dl             2020.5.29   
zeroconf               0.26.1      
zipp                   3.1.0
```

**Comment by minhducsun2002** [comment]
Identical error here.
```
$ python --version; pip --version
Python 3.8.3
pip 20.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```

```
$ discord-overlay
Traceback (most recent call last):
  File "/usr/bin/discord-overlay", line 5, in <module>
    from discord_overlay.discord_overlay import entrypoint
  File "/home/cipher/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/cipher/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /usr/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5
```

**Comment by trigg** [comment]
How are you installing on Arch?

I note now that [AUR](https://aur.archlinux.org/packages/discord-overlay-git/) has updated to use the new setup.py but I have not been able to test it myself.

**Comment by minhducsun2002** [comment]
I followed the instructions in README.

**Comment by legendofmiracles** [comment]
I cloned it from github, gonna try it from the aur.

**Comment by legendofmiracles** [comment]
It works from the aur, probably because it installs the right dependencies. Really Awesome. If it also works for @minhducsun2002 , i'll close this issue.

**Comment by minhducsun2002** [comment]
Sorry for the late reply. Will try the AUR this afternoon.

**Comment by minhducsun2002** [comment]
Yeah it works. @alx365 please close this issue.

**Comment by legendofmiracles** [comment]
Sure
