### ISSUE TITLE
installation keeps failing

### ISSUE THREAD

**Issue by yunusp** [trigg/DiscordOverlayLinux#44]
``` Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-hfgbj4k8/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hfgbj4k8/PyQt5/
```

how should i fix this?

**Comment by trigg** [comment]
More information would help. What Distro, version etc.

**Comment by yunusp** [comment]
@trigg  elementary os hera ubuntu 18.04.

**Comment by midget3111** [comment]
@yunusp running the following solved it for me -
`sudo pip3 install --upgrade pip && sudo pip3 install PyQt5`

**Comment by yunusp** [comment]
ok this worked, thanks :)

**Comment by midget3111** [comment]
No problem! I'll go ahead and close the issue :)
