### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by sfjuocekr** [trigg/DiscordOverlayLinux#64]
I'm getting the following error when trying to launch discord-overlay:

Traceback (most recent call last):
  File "/home/sjoer/.local/bin/discord-overlay", line 5, in <module>
    from discord_overlay.discord_overlay import entrypoint
  File "/home/sjoer/.local/lib/python3.8/site-packages/discord_overlay/__init__.py", line 1, in <module>
    from .discord_overlay import *
  File "/home/sjoer/.local/lib/python3.8/site-packages/discord_overlay/discord_overlay.py", line 23, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /lib/x86_64-linux-gnu/libQt5Quick.so.5: undefined symbol: _ZN4QRhi10newSamplerEN11QRhiSampler6FilterES1_S1_NS0_11AddressModeES2_, version Qt_5_PRIVATE_API

**Comment by sfjuocekr** [comment]
Going back to PyQt5-5.15.1 works
